[package]
name = "bitcoin-coordinator"
version = "0.8.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitcoincore-rpc = "0.19.0"
config = "0.15.13"
console = "0.16.0"
serde = "1.0.204"
serde_json = "1.0.96"
thiserror = "2.0.12"
tracing = "0.1.40"
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"] }
ctrlc = "3.4"
hex = "0.4.3"
uuid = { version = "1.11.0", features = ["v4", "serde"] }

rust-bitvmx-storage-backend = { git = "https://github.com/FairgateLabs/rust-bitvmx-storage-backend.git", tag = "v0.8.1" }
bitvmx-transaction-monitor = { git = "https://github.com/FairgateLabs/rust-bitvmx-transaction-monitor.git", tag = "v0.8.1" }
bitvmx-key-manager = { git = "https://github.com/FairgateLabs/rust-bitvmx-key-manager.git", tag = "v0.8.1" }
bitvmx-settings = { git = "https://github.com/FairgateLabs/rust-bitvmx-settings.git", tag = "v0.8.1" }
bitvmx-bitcoin-rpc = { git = "https://github.com/FairgateLabs/rust-bitvmx-bitcoin-rpc.git", tag = "v0.8.1" }
bitvmx-protocol-builder = { git = "https://github.com/FairgateLabs/rust-bitvmx-protocol-builder.git", tag = "v0.8.1" }


[dependencies.bitcoin]
version = "0.32.2"
features = ["rand-std", "serde"]

[dependencies.chrono]
version = "0.4.38"
features = ["serde"]

[dependencies.rand]
version = "0.9.2"
features = ["std", "std_rng"]

[dev-dependencies]
bitcoind = { git = "https://github.com/FairgateLabs/rust-bitcoind.git", tag = "v0.8.1" }
bitcoin-indexer = { git = "https://github.com/FairgateLabs/rust-bitcoin-indexer.git", tag = "v0.8.1" }
bitvmx-bitcoin-rpc = { git = "https://github.com/FairgateLabs/rust-bitvmx-bitcoin-rpc.git", tag = "v0.8.1", features = [
    "testing",
] }
